
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // In production on Cloudflare, Prisma uses the D1 adapter (no DATABASE_URL needed).
    // This fallback prevents `prisma generate` from crashing during the build.
    url: process.env.DATABASE_URL ?? "file:./dev.db",
  },
});
